### ISSUE TITLE
Strange behavior of HimemX

### ISSUE THREAD

**Issue by cyberluke** [Baron-von-Riedesel/HimemX#1]
Hi, can you please help? I'm trying to limit RAM / XMS in DOS 7.1 (Windows98SE real dos mode). I have Intel BX440 with Pentium III and 1 GB RAM. Games do not run or complain because of overflow of 1000000 MB number when getting total available memory.

I started thread at Vogons as well: https://www.vogons.org/viewtopic.php?f=7&t=83156

We found out different users have different results.

When I use /MAX parameter I get only Free XMS of 64M. Total XMS is still 1GB.

Death Rally will not install from original disc, it crash with fatal error that you need at least 8 MB of RAM for installation.

I have a longer list of not working apps, it is fifty fifty. Other machine with 128MB Ram works.

**Comment by Baron-von-Riedesel** [comment]
> When I use /MAX parameter I get only Free XMS of 64M. Total XMS is still 1GB.

No, the /MAX option limits total amount of XMS, not just free XMS. For example, setting
DEVICE=HIMEMX.EXE /MAX=31680
limits XMS memory to 31 MB - 64 kB, resulting in
1. conventional memory 1024 kB
2. HMA 64 kB
3. XMS 31680 kB

giving a total of 32 MB of memory.

**Comment by cyberluke** [comment]
Tried all versions, all parameters. /X2MAX32 /MAX=32767 and /MAX=65535 and /MAX=64535

HimemSX 3.52: same ill behavior
HimemX 3.34: same ill behavior
HimemX 3.34: same ill behavior
HimemX2 3.34: same ill behavior

Found a partial solution: in BIOS if I enable this strange option, everything starts to work. Installation of Death Rally no longer complains and I was able to finish whole process and even run the game.

I talk about this option: OS/2 Onboard memory > 64M: Enabled

Then it works no matter what HimemX version you use.

**Comment by cyberluke** [comment]
![himemx](https://user-images.githubusercontent.com/1111375/131009557-c458a512-7ad7-4c19-9732-665d29d63328.jpg)

Here as you can see it limits only FREE XMS, not TOTAL XMS.

**Comment by Baron-von-Riedesel** [comment]
> Here as you can see it limits only FREE XMS, not TOTAL XMS.

It's probably a problem with your MEM.EXE program - it might use BIOS interrupts to get amount of extended memory and interpret it as "XMS".
The XMSSTAT program coming with JemmEX will actually display amounts of memory using the XMS API, which is installed by HimemX.exe. And the XMS host is responsible for this API only.

**Comment by cyberluke** [comment]
It is Windows 98 SE system. This behavior results in a lot of DOS apps not working, unless enabling OS/2 Memory feature in BIOS. Therefore XMSSTAT is not solution for these issues. I tried to set /METHOD parameter to BIOS, but that did not solve it either.

**Comment by Baron-von-Riedesel** [comment]
> Therefore XMSSTAT is not solution for these issues.

XMSSTAT is just to display current XMS status, so you can see what the XMS host does actually report.

> I tried to set /METHOD parameter to BIOS, but that did not solve it either.

That parameter is for A20, totally unrelated to extended memory.

> unless enabling OS/2 Memory feature in BIOS

Ok, if that solves your issues, everything's fine now?

**Comment by cyberluke** [comment]
Good question. Probably yes. Windows 98 SE (with SP3) will boot and show 1024MB RAM in Computer properties. I will need to investigate this on other 10 computer here. As well as FreeDOS, which is not compatible with DOS games much. That is a separate task for me.

What I do not like that people recommend HimemX and/or XMSDSK to lower RAM to get some form of compatibility for running DOS apps. But that is not true as can be seen here. So for me it solves nothing and I get only 50% success rate for DOS apps unless enabling OS/2 Memory feature. 

Question is what happens on motherboard without this BIOS feature. I believe modern computer do not have this, so this will impact FreeDOS as well. I will investigate and drop the results in FreeDOS mailing list as well. It does not matter what XMS manager is used (JemmEx have same issues and less compatibility).

**Comment by Baron-von-Riedesel** [comment]
> Question is what happens on motherboard without this BIOS feature. 

Try tool MEMSTAT coming with JemmEx to see what impact this feature has for BIOS memory APIs!
Is the motherboard pre-ACPI (no support for Int 15h, ax=E820h)?

**Comment by cyberluke** [comment]
Yes, the board is pre-ACPI. Asus P2B-DS. Well, depends on revision. There
are revisions with broken ACPI suppport and require modifying resistor 80
or 79 to fix it. I think I have ACPI disabled in Bios, as well as APM. I
will double check that.

**Comment by cyberluke** [comment]
Hi, I got new evidence here:
![limitmem](https://user-images.githubusercontent.com/1111375/131223243-56d0ba52-9643-46e2-995f-594092bba31f.jpg)

R Loew's LIMITMEM.SYS works much better. HimemX/HimemSX/JemmEX - all these suffer from the same bug.

Download here:
http://lonecrusader.x10host.com/rloew/limitmem.html

Use like this to get my result:
DEVICE=C:\DRIVERS\LIMITMEM.SYS 32

So I would like to kindly insist that I found some bug :-)

**Comment by Baron-von-Riedesel** [comment]
> So I would like to kindly insist that I found some bug :-)

No. There's a huge misunderstanding on your side. This RLow tool hooks BIOS interrupt 15h, ax=E801h/E820h, while HimemX implements the - pretty well documented - XMS API. So these are different animals; himemX is NOT supposed to modify Int 15h.

I already mentioned tool MEMSTAT. This tool displays the values returned by BIOS int 15h, so you can see what values LIMITMEM.SYS does modify.

I think we can close this issue now.

**Comment by cyberluke** [comment]
But one of your himemx versions have this parameter for int15 with two
address choices, right? I try one and it did not work either.

**Comment by Baron-von-Riedesel** [comment]
> But one of your himemx versions have this parameter for int15 with two address choices, right? 

HimemX calls BIOS interrupt 15h to detect size of extended memory. Since there exist multiple BIOS int 15h APIs, one can optionally tell himemX to ignore one of them. But it's necessary to understand that himemX uses BIOS int 15h as INPUT only.

**Comment by cyberluke** [comment]
Ok thank you very much for your time and apologize for confusion.
