### ISSUE TITLE
Himem and Windows 3.x/9x issues on modern hardware

### ISSUE THREAD

**Issue by Mintsuki** [Baron-von-Riedesel/HimemX#2]
Hello!

I am sorry if this issue is out of place, I wanted to send an email instead, but I'm not the email kind of person so here goes. I am asking here because I have been completely out of luck trying to get an answer to this question anywhere else.

On modern Intel systems (I checked and it seems to be Skylake and newer) it would appear that `HIMEM.SYS` exhibits a weird behaviour where it hangs on the memory test if ran with no machine switch. Disabling the memory test causes it to load, but DOS, and subsequently ran programs (including `mem`), seem very unstable and crash prone.

Adding the `/M:1` switch to `HIMEM.SYS` causes it to seemingly load properly, with even a seemingly successful memory test. That said, trying to run Windows 3.x in 386 enhanced mode or any of the Windows 9x series OSes causes really weird crashes when trying to start them. Namely, Windows 3.x fails with `vga.drv failed to load`, back to MS-DOS prompt. Windows 9x fails with `While initializing VCACHE: Windows protection error`.

I have applied all of the classic patches for memory frequency and memory size issues, as well as trying to boot with as little as <512MB of physical DDR4 RAM by cutting down the reported memory size of the DIMM in its SPD, and underclocking the CPU, but no dice. I also disabled 32-bit disk access and all of that.

Considering these OSes run flawlessly under KVM (VT-x) virtualisation, it appears really weird to me that they wouldn't run on real hardware too, considering that the x86 ISA is the same. At this point, even if not possible to get them to run, I would just be curious to know what is causing them to refuse to start, and that is what I am asking with this lengthy (sorry lol) issue.

Any idea?

Thanks in advance.

**Comment by Baron-von-Riedesel** [comment]
This is definitely the wrong place for such questions.

I'm no expert in "running old MS OSes on new hardware".

There's not only the "memory size" issue to address, but also problems with hard disk size and FAT16/32 to solve. And, AFAIK, you won't get useful error messages from the Win3x OS.

**Comment by Mintsuki** [comment]
Yead I figured.

I don't think hard disk size is an issue considering I booted from relatively small USB drives.

Thanks anyways for the answer!
